### ISSUE TITLE
CUDA inference failure on 5070 Ti – pp-doclayout-v3 crashes with CUBLAS_STATUS_INVALID_VALUE

### ISSUE THREAD

**Issue by Kangayou** [mayocream/koharu#737]
Koharu launches successfully and partially uses GPU acceleration on an RTX 5070 Ti, but consistently fails during the pp-doclayout-v3 pipeline step with:

CublasError(CUBLAS_STATUS_INVALID_VALUE)

CPU fallback works correctly.

**OS**
Linux (KDE Plasma Wayland session)

**GPU**
NVIDIA GeForce RTX 5070 Ti

**Driver / CUDA**
Driver Version: 595.71.05
CUDA Version: 13.2
GPU compute capability: 12.0

Koharu initially failed to launch UI under Wayland with:
Gdk-Message: Error 71 (Protocol error) dispatching to Wayland display.
ERROR: WebKit encountered an internal error.

This was worked around successfully by launching with:
GDK_BACKEND=x11 WEBKIT_DISABLE_COMPOSITING_MODE=1 koharu

After this, the UI launches correctly, however processing an image consistently fails during pp-doclayout-v3.
speech-bubble-segmentation appears to execute successfully on GPU before the failure occurs.

This suggests:
CUDA initialization succeeds
GPU detection succeeds
at least some GPU inference paths work correctly

The crash appears isolated to the pp-doclayout-v3 model/runtime path.

This CPU fallback launch fully works:
CUDA_VISIBLE_DEVICES="" GDK_BACKEND=x11 WEBKIT_DISABLE_COMPOSITING_MODE=1 koharu

**Comment by rainbuilt** [comment]
This might be related to the CUDA/cuBLAS libraries bundled with Koharu, not just the driver installed on the system.

In my case, `nvidia-smi` showed CUDA 13.2 as well, but Koharu was still using the bundled CUDA 13.0-era runtime/cuBLAS libraries. The symptoms were very similar: GPU detection worked, some GPU inference paths ran fine, but `pp-doclayout-v3` failed with `CUBLAS_STATUS_INVALID_VALUE`.

I rebuilt Koharu after switching the bundled NVIDIA CUDA wheels to CUDA 13.2-era versions, and the `CUBLAS_STATUS_INVALID_VALUE` failure no longer occurred.

So it might be worth testing a build with newer bundled CUDA 13.x wheels, especially a newer `nvidia-cublas`, for RTX 50-series / Blackwell / compute capability 12.0 GPUs.

**Comment by rainbuilt** [comment]
These are wheelspec I tried on `koharu/koharu-runtime/src/cuda.rs`:
```rs
const WHEELS: &[WheelSpec] = &[
    WheelSpec {
        package: "nvidia-cuda-runtime/13.2.75",
        windows_dylibs: &["cudart64_13.dll"],
        linux_dylibs: &["libcudart.so.13"],
    },
    WheelSpec {
        package: "nvidia-cublas/13.4.0.1",
        windows_dylibs: &["cublasLt64_13.dll", "cublas64_13.dll"],
        linux_dylibs: &["libcublasLt.so.13", "libcublas.so.13"],
    },
    WheelSpec {
        package: "nvidia-cufft/12.2.0.46",
        windows_dylibs: &["cufft64_12.dll"],
        linux_dylibs: &["libcufft.so.12"],
    },
    WheelSpec {
        package: "nvidia-curand/10.4.2.55",
        windows_dylibs: &["curand64_10.dll"],
        linux_dylibs: &["libcurand.so.10"],
    },
    WheelSpec {
        package: "nvidia-cudnn-cu13/9.21.0.82",
        windows_dylibs: &[
            "cudnn64_9.dll",
            "cudnn_adv64_9.dll",
            "cudnn_cnn64_9.dll",
            "cudnn_engines_precompiled64_9.dll",
            "cudnn_engines_runtime_compiled64_9.dll",
            "cudnn_engines_tensor_ir64_9.dll",
            "cudnn_graph64_9.dll",
            "cudnn_heuristic64_9.dll",
            "cudnn_ops64_9.dll",
        ],
        linux_dylibs: &[
            "libcudnn.so.9",
            "libcudnn_adv.so.9",
            "libcudnn_cnn.so.9",
            "libcudnn_engines_precompiled.so.9",
            "libcudnn_engines_runtime_compiled.so.9",
            "libcudnn_engines_tensor_ir.so.9",
            "libcudnn_graph.so.9",
            "libcudnn_heuristic.so.9",
            "libcudnn_ops.so.9",
        ],
    },
];
```
